### ISSUE TITLE
Crash on load when using 1.3.2 version of blockshifter

### ISSUE THREAD

**Issue by Blugori** [LolHens/mc-blockshifter#20]
Hi, I ran into an issue while trying to add Blockshifter to my modpack. Minecraft crashed on loading screen.
(Minecraft didnt provide any crash log)

Minecraft : 1.16.4
Forge : 35.0.7
Blockshifter : 1.3.2

[debug.log](https://github.com/LolHens/mc-blockshifter/files/5506541/debug.log)
[latest.log](https://github.com/LolHens/mc-blockshifter/files/5506542/latest.log)

Best regards

**Comment by LolHens** [comment]
Hi, look like it is missing [Scalable Cat's Force](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force):
`latest.log L10: [08nov.2020 15:56:14.917] [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/]: Missing language kotori_scala version [2.13.3-build-1,) wanted by blockshifter-1.3.2+forge-1.16.4.jar`

Do you have that jar installed in your mods folder because that is a [requirement for this mod](https://github.com/LolHens/mc-blockshifter#forge).

**Comment by Blugori** [comment]
It worked fine ! Sorry for the inconvenience !
